### ISSUE TITLE
Docker image behind current version?

### ISSUE THREAD

**Issue by ZoyavanMeel** [goldman-gp-ebi/SWAMPy#9]
Hi! I just discovered your tool and would like to use it.

I managed to run the test files using Docker and it works great. However, it seems that this version is not in-sync with the current version of the repository. For example, my container has no ARTIC v5.3 support.

Would it be possible to update the Docker image? Or do you recommend a different installation method?

Thanks!
Zoya

**Comment by willboulton** [comment]
Hi Zoya, thanks! I'll try to update the Docker image as soon as possible, otherwise I would suggest that you could clone the repositry and use the conda installation... if you have a Mac or Linux it should be quite easy (follow the instructions in the README - with Mac it's slightly harder but the instructions are there), but if you have Windows you would need to use an environment like WSL - it might be easier to wait. 
Best wishes, 
Will

**Comment by ZoyavanMeel** [comment]
Hi Will,

Thank you so much! I think I will wait a bit then. I tried the Conda install via WSL but got stuck on the bit with ART. My preference is definitely towards Docker 😅

Have a nice day,
Zoya

**Comment by willboulton** [comment]
When you have time would you be able to pull the latest version, and see if that works? I've just pushed the current version to github, it should all be up to date and working now, but if it's not then let me know and I'll troubleshoot it. 

Also please have a look at Issue #8 because this is still a problem... if you want to run a simulation using the MiseqV3 then please use the following parameters `--seqSys custom --qprof1 MiSeqv3L250R1_reversed.txt  --qprof2 MiSeqv3L250R2_reversed.txt` (download these two text files from issue #8). 

Best regards, 
Will

**Comment by ZoyavanMeel** [comment]
Thanks a bunch! Just pulled it. The test files run and the new primers are present!

I'll keep that issue in mind as well, thanks again!
